name: Report Test Failures

on:
  workflow_run:
    workflows: ["CI", "Test", "Build"] # replace with your actual workflow names
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  report-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow logs
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.payload.workflow_run.id
            const { data } = await github.request(
              `GET /repos/${context.repo.owner}/${context.repo.repo}/actions/runs/${run_id}/logs`
            )
            core.setOutput("log_url", data.url)

      - name: Post comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_URL: ${{ steps.github-script.outputs.log_url }}
        run: |
          set -e

          # Find the PR(s) associated with this workflow run
          pr_numbers=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/pulls --jq '.[].number')

          if [ -z "$pr_numbers" ]; then
            echo "No PRs associated with this run. Skipping."
            exit 0
          fi

          for pr in $pr_numbers; do
            body="@codex we have a test failure\n\nLogs: [Download here]($LOG_URL)"
            gh api repos/${{ github.repository }}/issues/$pr/comments -f body="$body"
          done
