name: Report Test Failures

on:
  workflow_run:
    workflows: ["CI", "Test", "Build"] # replace with your workflow names
    types:
      - completed

permissions:
  actions: read       # required for /actions/runs/{id}/logs and pulls API
  contents: read
  pull-requests: write

jobs:
  report-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow logs
        id: fetch-logs
        run: |
          curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/logs" \
            -o logs.zip
          echo "log_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

      - name: Extract logs
        run: unzip -q logs.zip -d logs

      - name: Collect last 100 lines of failed logs
        id: collect
        run: |
          mkdir -p snippets
          # Pick most recently modified log file (usually failing step/job)
          failed_log=$(ls -t logs/**/*.txt | head -n 1)
          echo "Using log file: $failed_log"
          tail -n 100 "$failed_log" > snippets/failure_snippet.txt

          echo "snippet<<EOF" >> $GITHUB_OUTPUT
          cat snippets/failure_snippet.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_URL: ${{ steps.fetch-logs.outputs.log_url }}
          SNIPPET: ${{ steps.collect.outputs.snippet }}
        run: |
          set -e
          pr_numbers=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/pulls --jq '.[].number')

          if [ -z "$pr_numbers" ]; then
            echo "No PRs associated with this run. Skipping."
            exit 0
          fi

          for pr in $pr_numbers; do
            body="@codex we have a test failure\n\n<details><summary>Last 100 lines of failure log</summary>\n\n\`\`\`\n$SNIPPET\n\`\`\`\n</details>\n\n[View full logs]($LOG_URL)"
            gh api repos/${{ github.repository }}/issues/$pr/comments -f body="$body"
          done
