name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      DEV: "0"
      USER: runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure ffmpeg is available
        run: |
          if ! command -v ffmpeg >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings
